Local and social spy persistence
WiIIiam278/HuskChat pull request #30
Opened 2022-04-03 00:59 UTC by TrueWinter

This pull request adds local and social spy persistence, fixing #25.

While this might not be the best code (I haven't written Java in a while), I feel it implements the feature in a satisfactory way. It's been tested to work with Velocity, but should work with BungeeCord too.

The data is stored in a YAML file in the plugin's data directory, in the following format:
```yaml
social:
  bcb70186-ea67-4346-85c5-33edf9576526:
    color: DARK_GRAY
local:
  bcb70186-ea67-4346-85c5-33edf9576526:
    color: DARK_GRAY
```

2022-04-03 01:15 UTC, WiIIiam278 commented
Nice job here! I think this should do the job nicely - I'll have a look at this tomorrow in more detail

2022-04-07 12:23 UTC, WiIIiam278 requested changes
Looks great, nice work - just would like to polish up the logging to not leave any loose TODO ends hanging

2022-04-07 12:23 UTC, WiIIiam278 commented on common/src/main/java/net/william278/huskchat/player/PlayerCache.java
> +            e.printStackTrace();
Using the logger requires an instance of the logger class that's been adapted from the platform logger, which isn't doable nicely through the static implementation here. Best to just have these static methods throw an IOException and handle with try-catch where they're called on the platform specific classes

2022-04-07 12:23 UTC, WiIIiam278 commented on velocity/src/main/java/net/william278/huskchat/velocity/HuskChatVelocity.java
> +        PlayerCache.loadSpy();
Have loadSpy and removeSpy `throw IOException` and catch here / also in the bungee file. You can then properly handle the logging by getting the logger with the exception; `getLoggingAdapter().log(...)`

2022-04-07 14:47 UTC, TrueWinter commented
It now uses the logger for error messages.

2022-04-08 18:35 UTC, Iotados commented
Just want to bump this for review and for Merging if possible!

2022-04-08 18:57 UTC, WiIIiam278 commented
I got it, thanks iota. It's on the list of things to check :-)

2022-04-09 17:00 UTC, WiIIiam278 approved these changes

2022-04-09 17:00 UTC, merged